name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use PNPM
        uses: pnpm/action-setup@v2.2.4

      - run: pnpm install
      - run: pnpm run lint && pnpm run check && pnpm run build
