name: Node.js Package
on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]
  release:
    types: [created]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
    publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        uses: pnpm/action-setup@v2.2.4
        with:
          registry-url: 'https://npm.pkg.github.com'

      - run: pnpm install
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}