name: CI
on:
  push:
    branches:
      - "**"

concurrency: ${{ github.workflow }}-${{ github.ref }}


jobs:
    release:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest
      permissions:
        contents: write
        pull-requests: write
      steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use PNPM
        uses: pnpm/action-setup@v2.2.4

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install NPM Dependencies
        run: pnpm install

      - name: Check for errors
        run: pnpm check

      - name: lint checker
        run: pnpm lint

      - name: Build the package
        run: pnpm build

      - run: |
          echo @Samuele-Barbiera:https://npm.pkg.github.com/ > build/.npmrc
      - run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"

      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1.4.1
        with:
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          version: node .github/changeset-version.js
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: "production"